title: Thor's first custom github page
author: duannthor
email: dt@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is so much simpler than setting up a hosting site with Python & Flask. Does it have bootstrap4 enabled?
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
